name: Main

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    # Skip running on PR events that come from the same repository, it will just duplicate the branch action
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name

    steps:
    - name: "Checkout"
      uses: actions/checkout@v4
    - name: "Setup cache"
      uses: actions/cache@v4
      id: cache-deps
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install gcc-mingw-w64
    - name: Build
      run: cargo build --verbose --release --target x86_64-pc-windows-gnu
    - name: Run Clippy
      run: cargo clippy --target x86_64-pc-windows-gnu
    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: LauncherTweaks
        path: |
          LICENSE
          README.md
          target/x86_64-pc-windows-gnu/release/winmm.dll
        if-no-files-found: error
